function varargout = test(varargin)
% VL_TEST  Run test suite
%  RESULTS = VL_TEST() runs all VLFeat test suites. The tests
%  verify that VLFeat is working correctly.
%
%  RESULTS is a structure listing the result of each test,
%  as generated by the MATLAB Unit Test framework. failed
%
%  VL_TEST(PAR,VAL,...) supports the following options:
%
%  Break:: false
%    Set to true to break on failure.
%
%  TapFile:: []
%    Specify an optional TAP file to record the test results.
%
%  Command:: []
%    Specify an optional prefix for the test command to run.
%    For example, `vl_test('command','vl_test_aib')` only runs
%    the `vl_test_aib` tests.
[varargout{1:nargout}] = vl_test(varargin{:});
